### ISSUE TITLE
Remove an offensive word

### ISSUE THREAD

**Issue by amire80** [apertium/apertium-rus-ukr#1]
Hi,

The word "Russian" is sometimes translated as "москаль". I understand that this word exists in Ukrainian and that in some very particular contexts it may be a correct translation, but most of the time, it's just incorrect and unnecessarily offensive.

Here's a consistently reproducible example.

Russian input: "Вход в чаты свободный (однако не забудьте представиться и кратко рассказать о себе, если пришли впервые), рабочий язык — русский."
Ukrainian output: "Вхід у чаты свободный (однак не забудьте представиться #і коротке розказати о собі, якщо прийшли вперше), робітниця мову — москаль."

There are some other mistakes here, but the last word is the worst.

**Comment by ftyers** [comment]
Fixed in ff65570. I just commented out for now. But when it recompiles that word should not be generated.
